config/routes.rb
Rails.application.routes.draw do
  get 'tabedit/:id', to: 'tasks#tabedit'
  
  resources :tasks

  root to: 'tasks#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @task = Task.first
    @tasktest = Task.first
    @incomplete_tasks = Task.where(complete: false)
    @complete_tasks = Task.where(complete: true)
    
    
  end

  def new
    @task = Task.new
  end

def create
  
  
  @task = Task.create!(allowed_params)

  respond_to do |f|
    f.html { redirect_to tasks_url }
    f.js
  end
end

def update
  
  @task = Task.find(params[:id])
  @task.update_attributes!(allowed_params)
  
  
  respond_to do |f|
    f.html { redirect_to tasks_url }
    f.js
  end
end
  
def destroy
  @task = Task.destroy(params[:id])

  respond_to do |f|
    f.html { redirect_to tasks_url }
    f.js
  end
end

def tabEdit
  @task = Task.find(params[:id])

  respond_to do |f|
    f.html
    f.js
  end  


end

  def show
    @task = Task.find(params[:id])
 
    respond_to do |format|
      format.html
      format.js { render layout: false, content_type: 'text/javascript' }
    end
  end

  private

  def allowed_params
    params.require(:task).permit(:id, :title, :name, :complete, :date_received, :project, :delivery_date, :due_date, :requester, :category, :task_type, :output, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>OTIF Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  </head>

  <body>



<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-opencart"></i> OTIF Tracker</a>
            </li>
        </ul>
    </div>

    <div class="navbar-collapse collapse w-100 dual-collapse2">
        <ul class="navbar-nav ml-auto">

            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle text-warning" role="button" data-toggle="dropdown" href="#"><i class="fa fa-hand-scissors-o"></i> Change User</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">NormalUser1</a>
                    <a class="dropdown-item" href="#">TeamLeader1</a>
                  </div>            
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-question"></i> Help</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="homeNavbarDropdown" role="button" data-toggle="dropdown" href="#"><i class="fa fa-user"></i> NormalUser1</a>
                  <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fa fa-cog"></i> Configuration</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-line-chart"></i> Performance</a>
                  </div>
            </li>
        </ul>
    </div>
</nav>

    
    
    
    <%= yield %>
    

    
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update" %>
  <%= f.label :complete, task.name %>
  <%= link_to "(remove)", task, method: :delete, remote: true %>
<% end %>

app/views/tasks/_taskform.html.erb
<div class='tab-content' id='main-tab-content'>
  <div class='tab-pane fade show active container-fluid' id='home'>
        <button class='btn btn-primary' onclick=''><i class='fa fa-refresh'></i> Reload</button>    
        <button class='btn btn-primary' id='TASK<%= @task.task_ID %>-tab-save-btn'><i class='fa fa-save'></i> Save</button>
        <button class='btn btn-primary'><i class='fa fa-file-o'></i> Save & Close</button> 
        <button class='btn btn-primary'><i class='fa fa-window-close'></i> Close without Saving</button>  
        <button class='btn btn-primary'><i class='fa fa-ban'></i> Cancel</button>
<br><br>

      <form class='bd-example border border-primary'>

        <div class='row align-items-center'>
          <div class='col-6'>
            <h3>Task #<%= @task.task_ID%></h3>
          </div>
          <div class='col-6'>
            
          </div>
        </div>
      
        <div class='row align-items-center'>
          <div class='col-1'>
            <label for='TaskID-display'>Task ID:</label>
          </div>
          <div class='col-1'>
            <input type='text' class='form-control' id='TASK<%= @task.task_ID %>_ID_display' readonly value='<%= @task.task_ID %>'>
          </div>
          <div class='col-1'>
            <label for='owner-display'>Owner:</label>
          </div>
          <div class='col-1'>
            <input type='text' class='form-control' id='TASK<%= @task.task_ID %>_owner-display' readonly value='<%= @task.initials %>'>
          </div>
          <div class='col-8'>
          </div>
      
        </div>
        
        <div class='row align-items-center' id='Row2'>
          <div class='col-1'>
            <label for='title-display'>Task Title:</label>
          </div>
      
          <div class='col-5'>
            <input type='text' class='form-control small-input'  id='TASK<%= @task.task_ID %>_title_display' value='<%= @task.title %>'>
          </div>
          
          <div class='col-2'>
            <label for='date-received-display'>Date Received:</label>
          </div>
          <div class='col-2'>
            <input type='date' class='form-control' id='TASK<%= @task.task_ID %>_date_received_display' value='<%= @task.try(:date_received).try(:strftime, '%Y-%m-%d') %>'>
          </div>
          
        </div>  
      
        <div class='row align-items-center' id='Row3'>
          <div class='col-1'>
            <label>Project</label>
          </div>
      
          <div class='col-5'>
            <input type='text' class='form-control small-input' id='TASK<%= @task.task_ID %>_project_display' value='<%= @task.project %>'>
          </div>
          
          <div class='col-2'>
            <label>Expected Delivery Date</label>
          </div>
          <div class='col-2'>
            <input type='date' class='form-control' id='TASK<%= @task.task_ID %>_expected_date_display' value='<%= @task.try(:due_date).try(:strftime, '%Y-%m-%d') %>'>
          </div>
        </div> 
      
        <div class='row align-items-center' id='Row4'>
          <div class='col-1'>
            <label>Requester</label>
          </div>
      
          <div class='col-5'>
            <input type='text' class='form-control small-input' id='TASK<%= @task.task_ID %>_requester_display' value='<%= @task.requester %>'>
          </div>
          
          <div class='col-6'>

          </div>
        </div> 
      
        <div class='row align-items-center' id='Row5'>
          <div class='col-1'>
            <label>Category</label>
          </div>
      
          <div class='col-5'>
            <select class='form-control' id='TASK<%= @task.task_ID %>_category_display'>
              <option value='Cat One' <%= if @task.category=='Cat One' then 'Selected' else '' end %>>Cat One</option>
              <option value='Cat Two' <%= if @task.category=='Cat Two' then 'Selected' else '' end %>>Cat Two</option>
              <option value='Cat Three' <%= if @task.category=='Cat Three' then 'Selected' else '' end %>>Cat Three</option>
            </select>
          </div>
          
          <div class='col-6'>

          </div>

        </div> 
      
        <div class='row align-items-center' id='Row6'>
          <div class='col-1'>
            <label for='type-display'>Task Type</label>
          </div>
      
          <div class='col-5'>
            
            <select class='form-control' id='TASK<%= @task.task_ID %>_task_type_display'>
              <option value='Type One' <%= if @task.task_type=='Type One' then 'Selected' else '' end %>>Type One</option>
              <option value='Type Two' <%= if @task.task_type=='Type Two' then 'Selected' else '' end %>>Type Two</option>
              <option value='Type Three' <%= if @task.task_type=='Type Three' then 'Selected' else '' end %>>Type Three</option>
            </select>            
            
          </div>
          
          <div class='col-6'>

          </div>

        </div> 
      
        <div class='row align-items-center' id='Row7'>
          <div class='col-1'>
            <label for='output-display'>Output</label>
          </div>
      
          <div class='col-5'>

            <select class='form-control' id='TASK<%= @task.task_ID %>_output_display'>
              <option value='Documentation' <%= if @task.output=='Documentation' then 'Selected' else '' end %>>Documentation</option>
              <option value='Report' <%= if @task.output=='Report' then 'Selected' else '' end %>>Report</option>
            </select>   

          </div>
          
          <div class='col-6'>
          </div>
          
        </div> 
        
        <div class='row align-items-center' id='Row8'>
          <div class='col-1'>
            <label for='description-display'>Description</label>
          </div>
      
          <div class='col-5'>
            <textarea class='form-control' rows='3' id='TASK<%= @task.task_ID %>_description_display'><%= @task.description %></textarea>
          </div>
          
          <div class='col-6'>
          </div>
          
        </div>   
        
      </form>

      
  </div>
</div>     
<br>

      
<script>
  $('#TASK<%= @task.task_ID %>-tab-save-btn').click(function (e) {

    $.ajax({
    type: 'PUT',
    dataType: 'script',
    url: '/tasks/<%= @task.id %>',
    contentType: 'application/json',
    data: JSON.stringify({ authenticity_token: $('[name="csrf-token"]')[0].content, id: <%= @task.id %>, 
    title: $('#TASK<%= @task.task_ID %>_title_display').val(), 
    date_received: $('#TASK<%= @task.task_ID %>_date_received_display').val(),
    project: $('#TASK<%= @task.task_ID %>_project_display').val(),
    due_date: $('#TASK<%= @task.task_ID %>_expected_date_display').val(),
    requester: $('#TASK<%= @task.task_ID %>_requester_display').val(),
    category: $('#TASK<%= @task.task_ID %>_category_display').val(),
    task_type: $('#TASK<%= @task.task_ID %>_task_type_display').val(),
    output: $('#TASK<%= @task.task_ID %>_output_display').val(),
    description: $('#TASK<%= @task.task_ID %>_description_display').val(),    

    }) 

    });

});  
 
    
</script>
    
    
    

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

$("#example-table").tabulator("addRow", {name:"<%= @task.name %>", id:"<%= @task.id %>"}, false);

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

var row = $("#example-table").tabulator("getRow", <%= @task.id %>);
row.delete();

app/views/tasks/index.html.erb
<ul class="nav nav-tabs bg-primary" id="myTab">
  <li class="nav-item">
    <a class="nav-link text-white bg-primary active" id="home-tab" data-toggle="tab" href="#home"><i class="fa fa-home"></i> Home</a>
  </li>

</ul>

<div class="tab-content" id="main-tab-content">
  <div class="tab-pane fade show active container-fluid" id="home">
        <button class="btn btn-primary" id="home-refresh-button"><i class="fa fa-refresh"></i> Reload</button>
        <button class="btn btn-primary"><i class="fa fa-file"></i> New</button>
        <button class="btn btn-primary" id="home-open-button"><i class="fa fa-edit"></i> Open</button>        
        <button class="btn btn-primary"><i class="fa fa-ban"></i> Cancel</button>
        <br>
        <div id="example-table" class="table-bordered table-sm border border-primary"></div>
  </div>
</div>




<script>

var currentTab;
var composeCount = 0;
//initilize tabs
var currentTab;
var composeCount = 0;
//initilize tabs
$(function () {

    //when ever any tab is clicked this method will be call
    $("#myTab").on("click", "a", function (e) {
        e.preventDefault();

        $(this).tab('show');
        $currentTab = $(this);
    });


    registerComposeButtonEvent();
    registerCloseEvent();
});

//this method will demonstrate how to add tab dynamically
function registerComposeButtonEvent() {
    /* just for this demo */
    $('#composeButton').click(function (e) {
        e.preventDefault();

        var tabId = "compose" + composeCount; //this is id on tab content div where the 
        composeCount = composeCount + 1; //increment compose count

        //$("#myTab").append('<li class="nav-item"><a class="nav-link" id="newTabRecord-tab" data-toggle="tab" href="#newTabRecord" role="tab">NewOne</a></li>');
        $("#myTab").append('<li class="nav-item"><a class="nav-link" id="newTabRecord-tab" data-toggle="tab" href="#newTabRecord" html="Some Text" role="tab"></a></li>');


        
        $("#myTabContent").append('<div class="tab-pane fade" id="newTabRecord" role="tabpanel">Some Text</div>');


        //craeteNewTabAndLoadUrl("", "#", "#newTabRecord");

        //$(this).tab('show');
        //showTab("newTabRecord");
        //registerCloseEvent();
    });

}

//this method will register event on close icon on the tab..
function registerCloseEvent() {


    $(document).on('click', '.closeTab', function() {

        //there are multiple elements which has .closeTab icon so close the tab whose close icon is clicked
        var tabContentId = $(this).parent().attr("href");
        $(tabContentId).remove(); //remove respective tab content
        $(this).parent().parent().remove(); //remove li of tab
        $('#myTab a:last').tab('show'); // Select last tab
     

    });
}

//shows the tab with passed content div id..paramter tabid indicates the div where the content resides
function showTab(tabId) {
    $('#myTab a[href="#' + tabId + '"]').tab('show');
}
//return current active tab
function getCurrentTab() {
    return currentTab;
}

//This function will create a new tab here and it will load the url content in tab content div.
function craeteNewTabAndLoadUrl(parms, url, loadDivSelector) {

    $("" + loadDivSelector).load(url, function (response, status, xhr) {
        if (status == "error") {
            var msg = "Sorry but there was an error getting details ! ";
            $("" + loadDivSelector).html(msg + xhr.status + " " + xhr.statusText);
            $("" + loadDivSelector).html("Load Ajax Content Here...");
        }
    });

}

//this will return element from current tab
//example : if there are two tabs having  textarea with same id or same class name then when $("#someId") whill return both the text area from both tabs
//to take care this situation we need get the element from current tab.
function getElement(selector) {
    var tabContentId = $currentTab.attr("href");
    return $("" + tabContentId).find("" + selector);

}


function removeCurrentTab() {
    var tabContentId = $currentTab.attr("href");
    $currentTab.parent().remove(); //remove li of tab
    $('#myTab a:last').tab('show'); // Select first tab
    $(tabContentId).remove(); //remove respective tab content
}

function saveData(){



rowsEdited.forEach(function(task_ID) {

var name = $("#example-table").tabulator("getRow", task_ID).getData().name;    


$.ajax({
    type: "PUT",
    dataType: "script",
    url: '/tasks/' + task_ID,
    contentType: 'application/json',
    data: JSON.stringify({ authenticity_token: $('[name="csrf-token"]')[0].content, id: task_ID, name: name })
});

});





};

function addNewRow() {
  $("#example-table").tabulator("addData", [{id:"", name:"", delete:""}], false);
  

};

Tabulator.extendExtension("format", "formatters", {
    file:function(cell, formatterParams){
        return "<a data-remote='true' rel='nofollow' data-method='delete' href='/tutorials/228'>Delete</a>";
    },
});

var printIcon = function(cell, formatterParams){ //plain text value
    return "<a data-remote='true' rel='nofollow' data-method='delete' href='/tasks/4'>(remove)</a>";
};

var rowsEdited = [];

//Create Date Editor
var dateEditor = function(cell, onRendered, success, cancel){
    //cell - the cell component for the editable cell
    //onRendered - function to call when the editor has been rendered
    //success - function to call to pass the succesfully updated value to Tabulator
    //cancel - function to call to abort the edit and return to a normal cell

    //create and style editor
    var editor = $("<input type='date'></input>");
    editor.css({
        "padding":"3px",
        "width":"100%",
        "box-sizing":"border-box",
    });

    //Set value of editor to the current value of the cell
    editor.val(moment(cell.getValue(), "DD/MM/YYYY").format("YYYY-MM-DD"));

    //set focus on the select box when the editor is selected (timeout allows for editor to be added to DOM)
    onRendered(function(){
      editor.focus();
      editor.css("height","100%");
    });

    //when the value has been set, trigger the cell to update
    editor.on("change blur", function(e){
        success(moment(editor.val(), "YYYY-MM-DD").format("DD/MM/YYYY"));
    });

    //return the editor element
    return editor;
};


//create Tabulator on DOM element with id "example-table"
$("#example-table").tabulator({

    layout:"fitColumns", //fit columns to width of table (optional)
    movableColumns: true, //enable user movable columns
    selectable:1,
    columns:[ //Define Table Columns
        {title:"ID", field:"id", width:50, visible:false},
        {title:"ID", field:"task_id", width:50},
        {title:"Owner", field:"initials",  headerFilter:"input", headerFilterPlaceholder:" ", width:75},
        {title:"Status", field:"status",  headerFilter:"input", headerFilterPlaceholder:" ", width:75},
        {title:"Progress", field:"progress", align:"left", formatter:"progress", width:85,  editable:true},
        {title:"Title", field:"title", headerFilter:"input", headerFilterPlaceholder:" ", width: 200},
        {title:"Project", field:"project", headerFilter:"input", headerFilterPlaceholder:" ", width:150},
        {title:"Category", field:"category"},
        {title:"Type", field:"type"},
        {title:"Due Date", field:"due_date"},

            ],
    cellEdited:function(cell){
        //cell - cell component
         var cellElement = cell.getElement();
        cellElement.css({"background-color":"#A6A6DF"});

        
        //var row = cell.getRow();
        //row.getElement().css({"background-color":"#A6A6DF"});
        
        var task_ID =  cell.getRow().getData().id;
        rowsEdited.indexOf(task_ID) === -1 ? rowsEdited.push(task_ID) : console.log("This item already exists"); 

    },

    rowClick:function(e, row){ //trigger an alert message when the row is clicked
        var row = $("#example-table").tabulator("getRow", row.getData().id); //return row compoenent with index of 1
        var rowData = row.getData();

        $('#title-display').val(rowData.title);
        $('#project-display').val(rowData.project);
        $('#category-display').val(rowData.category);        
        $('#type-display').val(rowData.type); 
        $('#output-display').val(rowData.output); 
        $('#expected-date-display').val(rowData.due_date.substring(0, 10)); 

        
    },    
    
        rowDblClick:function(e, row){
        //e - the click event object
        //row - row component
        
        // alert("doubleclick on row " + row.getData().id);
        $.ajax({
          type: "GET",
          dataType: "script",
          url: '/tasks/' + row.getData().id,
          contentType: 'application/json',
          data: JSON.stringify({ authenticity_token: $('[name="csrf-token"]')[0].content }) //, id: row.getData().id
        });
    },    
    
    
});

//define some sample data
var tabledata = [
    <% @tasks.each do |task| %>
        {id:"<%= task.id %>", task_id:"<%= task.task_ID %>", initials:"<%= task.initials %>", title:"<%= task.title %>", project:"<%= task.project %>", category:"<%= task.category %>", type:"<%= task.task_type %>", 
        due_date:"<%= task.try(:due_date).try(:strftime, '%Y-%m-%d') %>", status:"<%= task.status %>", progress:"<%= task.progress %>" },
    <% end %>

];

//load sample data into the table
$("#example-table").tabulator("setData", tabledata);

$('#home-open-button').click(function (e) {
    var selectedData = $("#example-table").tabulator("getSelectedData");
    
    $.ajax({
      type: "GET",
      dataType: "script",
      url: '/tasks/' + selectedData[0].id,
      contentType: 'application/json',
      data: JSON.stringify({ authenticity_token: $('[name="csrf-token"]')[0].content }) 
    });    
    

});



$('#home-temp-button').click(function (e) {
    alert("Save clicked");

    $.ajax({
    type: 'PUT',
    dataType: 'script',
    url: '/tasks/1',
    contentType: 'application/json',
    data: JSON.stringify({ authenticity_token: $('[name="csrf-token"]')[0].content, id: 1, date_received: 'testing' }) 

    });


});  
</script>
           

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'form' %>
<p><%= link_to "Back to tasks", tasks_path %></p>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/tasks/remove.tabedit.html.erb
<h1>Working...</h1>

app/views/tasks/show.html.erb
<h1>this is show</h1>

app/views/tasks/show.js.erb
        $("#myTab").append('<li class="nav-item"><a class="nav-link  text-white bg-primary" id="TASK<%= @task.task_ID %>-tab" data-toggle="tab" href="#TASK<%= @task.task_ID %>-tab-content"></a></li>');
        $("#TASK<%= @task.task_ID %>-tab").html('<i class="fa fa-file-text-o"></i> TASK<%= @task.task_ID %><button class="close closeTab text-white" type="button" >&#xd7</button>');
        
        $("#main-tab-content").append('<div class="tab-pane fade" id="TASK<%= @task.task_ID %>-tab-content"></div>');
        
        $('#TASK<%= @task.task_ID %>-tab').tab('show');
        

        
        $("#TASK<%= @task.task_ID %>-tab-content").append('<%= j render(:partial => 'taskform') %>');

app/views/tasks/tabedit.js.erb
        $("#myTab").append('<li class="nav-item"><a class="nav-link" id="newTabRecord-tab" data-toggle="tab" href="#newTabRecord" role="tab"><button class="close closeTab" type="button" >×</button>NewOne</a></li>');

        
        $("#myTabContent").append('<div class="tab-pane fade" id="newTabRecord" role="tabpanel">Some Text</div>');

alert("This is tabEdit js");

app/views/tasks/update.js.erb
console.log("From update.js.erb:" + <%= @task.id %>);



<!--var row = $("#example-table").tabulator("getRow", <%= @task.id %>);-->
<!--row.getElement().css({"background-color":"#fff"});-->

        <!-- var cellElement = $("#example-table").tabulator("getRow", <%= @task.id %>);-->
        <!--cellElement.css({"background-color":"#A6A6DF"});-->

var row = $("#example-table").tabulator("getRow", <%= @task.id %>);
var cell = row.getCell("name");
var cellElement = cell.getElement();
cellElement.css({"background-color":"#fff"});